#!/usr/bin/ruby

require 'net/http'
require 'uri'
require 'yaml'

search_uri = URI.parse('http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=' << ARGV[0] << URI.escape(' site:apple.com'))
response = Net::HTTP.get_response(search_uri)

results = (YAML.load(response.body))['responseData']['results']

`open #{results[0]['url']}`
